### ISSUE TITLE
A `simplfy` argument?

### ISSUE THREAD

**Issue by KevCaz** [ropensci/rcites#11]
Currently most of the functions use the flexibility of matrix/data.frame/data.table and store information as lists. This is very useful for us to make the code short, this may however bewilder some users. 

What we could do is to add an argument `simplify` so the data.tables we output have columns that are **not** lists when it is possible. What do you think?

**Comment by ibartomeus** [comment]
I think this is a good idea, but for me is a low priority thing to add.

**Comment by KevCaz** [comment]
#13 introduces it. Let's wait and see if this will be useful!

**Comment by KevCaz** [comment]
It uses pretty much everywhere since #15, I am therefore closing this.
