### ISSUE TITLE
Submit the package

### ISSUE THREAD

**Issue by ibartomeus** [ropensci/rcites#12]
The process is described here: 

https://github.com/ropensci/onboarding#how-submit

Looks easy, but we need to check the guidelines first. Also, What do you think about submitting to JOSS (which is the same process)? For me and given the nature of this package, would be enough. This would give us a DOI, a line in our CV under peer-reviewed papers and a to be indexed in G scholar.

I am skeptical MEE would be interested. I am not sure which other Journals accept quick notes on R packages.

**Comment by KevCaz** [comment]
JOSS + Ropensci... sounds like a plan!

>  This would give us a DOI [...]

Note that you can always add a DOI to your code using Zenodo!


By the way, if I recall correctly, the R client for the cites API was in the wishing of Ropensci, right?

**Comment by ibartomeus** [comment]
Yes, It was.

**Comment by KevCaz** [comment]
So I have to stop working on the package for today but I can finish to boost the code coverage this week-end + improve the documentation. Then I'll consider the package as ¨submittable¨. What's your feeling?

**Comment by ibartomeus** [comment]
Kevin, thanks so much for all the effort you put! I didn't test it yet, but I am happy to submit it sooner than later. We should also clarify authorship and give credit appropriately, especially to Kevin and Jonas.

**Comment by KevCaz** [comment]
I was happy to learn a bit more about web API and how to wrap around an API, so my pleasure!

I'll take care of the tests and double check the doc of our functions. If you have a good example in mind of what a user/researcher could do with this package, we should use it to build a vignette!

**Comment by KevCaz** [comment]
To me, we only need to build a nice / exhaustive vignette and we are ready to go.

**Comment by ibartomeus** [comment]
Awesome, I am swamped this week, but I can try to do the vignette next week. @JonasGeschke , what do you think about submitting to JOSS?

**Comment by KevCaz** [comment]
I'll try to outline the vignettes this week.

**Comment by KevCaz** [comment]
They make the submission quite easy! 
https://joss.theoj.org/about#author_guidelines

**Comment by JonasGeschke** [comment]
Hi guys,
so sorry for my absence during the past months.
Submitted our projects period extension application last week (lots work past months) and I was in Colombia during March.
JOSS sounds good, I would however also check out and have a quick chat with MEE about it. Will then draft a manuscript about CITES, its database and our package.
Best greetings!

**Comment by KevCaz** [comment]
I may be able to write a little bit more about the vignette soon (within two weeks). 
Any time frame for the ms?

**Comment by KevCaz** [comment]
I may be able to put a little bit of energy in this project this summer, are you interested in finish this up by the end of the summer?

**Comment by JonasGeschke** [comment]
totally!
I think we should meet for a skype to discuss progress.?
best greetings,
Jonas

**Comment by KevCaz** [comment]
Sure!
I'll be at the ESA by the way.

**Comment by ibartomeus** [comment]
Yes, and sorry for not kepig up with the project. Would be great to wrap it up and make it available. We can Skype this week anytime.

**Comment by KevCaz** [comment]
What about Thursday? I guess you are both in Europe. What about 2pm in Madrid (i.e. 8am here in Guelph)?

**Comment by JonasGeschke** [comment]
What about next week? This week I am in Hannover for a workshop about interactive biodiversity research web platforms.
Next week I am pretty flexible.

**Comment by KevCaz** [comment]
Next week works for me!

**Comment by ibartomeus** [comment]
ok, I am not sure If I will have internet, but if I do (hopefully), Monday 2 pm should be ok. If I can't make go ahead without me. My skype name is nachobartomeus

**Comment by KevCaz** [comment]
works for me.

**Comment by JonasGeschke** [comment]
So it is monday, 12pm (Europen/ Berlin time, right?). my skype is „jonasgeschke“.
looking forward to following up on this!

**Comment by ibartomeus** [comment]
14:00 to be clear.

**Comment by KevCaz** [comment]
See you tomorrow

**Comment by ibartomeus** [comment]
Papers: look for Tella et al., is on parrots as invasive species. I'll see to find it when I got decent internet.

**Comment by JonasGeschke** [comment]
great, thanks, I will check on this and find my way!

**Comment by JonasGeschke** [comment]
FYI: I contacted the coordinator of Methods in Ecology and Evolution in order to ask about publishing there. See the answer below.
So I guess we go with JOSS and then probably promote the publication via their blog.
Best greetings!

- - - - -
Hi Jonas,
 
Thank you for your email. It's wonderful to hear that your package is close to being ready for submission to rOpenSci or CRAN.
 
There are no publication fees for Methods in Ecology and Evolution unless you choose to make your article open access after submission. Your paper would fall under our ‘Applications’ article type, so it would be made freely available to the public upon publication (although not open access, as it would be published under a different license agreement). You can find out more about Applications articles here: https://besjournals.onlinelibrary.wiley.com/hub/journal/2041210x/author-guidelines#Article_types
 
The requirements for initial submission can be found here: https://besjournals.onlinelibrary.wiley.com/hub/journal/2041210x/author-guidelines#Quick_checklist
 
And you can see our aims and scope here: https://besjournals.onlinelibrary.wiley.com/hub/journal/2041210X/aims-and-scope/read-full-aims-and-scope
 
If you would like one of the Senior Editors to comment on whether your manuscript would be suitable for the journal, you just need to send us the abstract. I’ll then pass it along and let you know when I hear back from them.
 
Regardless of where you choose to submit a paper about your package, we would be happy to promote it through our social media channels and our blog. You can see how we have promoted a couple of other packages that arose from the hackathon here: https://methodsblog.wordpress.com/tag/hackathon/
 
I hope that this email has been helpful. If you have any further questions, just let me know.
 
Best wishes,
Chris

**Comment by KevCaz** [comment]
Sounds like a very good plan to me, thanks Jonas!

**Comment by KevCaz** [comment]
JOSS has a new authors guidelines webpage https://joss.readthedocs.io/en/latest/submitting.html

**Comment by JonasGeschke** [comment]
Thanks, I know, the link and paras aboout whats needed are already copied into the manuscript as info lines. I think the manuscript is quite alright already, but Ignasi should have a look at it.
Then we just need to check on the functioning of the package and the vignette. The storage on github already is sufficient, do we want to submit it to CRAN? (how long would this need?)

**Comment by KevCaz** [comment]
The submission to the CRAN doesn't worry me. Actually our package is ready for CRAN submission, and the steps to go through are fairly simple: https://cran.r-project.org/submit.html
However I would wait as there is still some work I want to do before submission!

**Comment by JonasGeschke** [comment]
Sure, no worries. Lets try to …
1. Finalise the paper manuscript until the 20.7.
2. Test the package and adapt the vignette until 27.7.
3. Thereafter submit the package to CRAN
4. Once we have the CRAN-link, submit the paper

**Comment by KevCaz** [comment]
I've built a website with pkgdown, to add it I need you do something @ibartomeus !
Whenever you have some time to do so: 
1. go to the settings of the repo 
2. enable gh-pages for this repo, select the option using a `docs` folder 
3. it'll give you a url you should but on the first page (top right next to the short description)

More details here => https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

Cheers

**Comment by ibartomeus** [comment]
I think it's done. I also gave you both admin privileges.

I edited (minimally) the ms, help, and vignettes. I also placed Kevin as the second author if you agree. The package is working nicely. I think we are ready on my part!

The last issue is about coauthors. I noticed I don't have all peoples email, so if you agree I'll ask the 8 collaborators listed if they want to be coauthors by naming them in an issue. 

Great job guys! It was a pleasure collaborating with you two!

**Comment by ibartomeus** [comment]
Update: It looks like I can not give you owner privileges (if you know a way, let me know).

Also, here is the webpage: https://ibartomeus.github.io/citesr/

**Comment by KevCaz** [comment]
Can you add this on the top of the home page of the repo?

**Comment by JonasGeschke** [comment]
ohh its getting to many conversations streams/ issues now ...
somewhere I read about the token: I agree the token is personal and should not be screened. Either we take a placeholder instead or - which I think would be fine - we just use ***** instead of the last 5 characters. @KevCaz can you edit this? (as it also needs to be in in the website)

**Comment by JonasGeschke** [comment]
@KevCaz in the website citation info https://ibartomeus.github.io/citesr/authors.html some link to another package "inSilecoMisc" is provided. I guess there should be some other reference ...

**Comment by KevCaz** [comment]
My bad!

**Comment by KevCaz** [comment]
done

**Comment by JonasGeschke** [comment]
how do you access and edit the website? cause the one "Access" needs to be written small "a".
and in general: I wonder if we should chance the creation date of the package so it becomes a 2018 in the citation. e.g. to the submission date to CRAN? I dont know ;-)

tell me if you need me to do anything further. I am gone over the weekend and back available on monday. would be great to submit the paper (with CRAN link?!) on thuesday or wednesday!

**Comment by KevCaz** [comment]
I'll follow your suggestions and I'll do some final change so everything is ready on Monday! Enjoy your week-end!!

**Comment by KevCaz** [comment]
@JonasGeschke you do not access the website, you simply build it using [pkgdown](https://github.com/r-lib/pkgdown), using `build_site()` (a convenient wrapper). Basically it takes different piece of the documentation and build a website, isn't it neat? This means that if you want to change anything, you need to change the relevant piece of documentation! For instance, if you aim at editing the home page, then you edit README.md!

**Comment by KevCaz** [comment]
I'm ready for the submission once I have your feedback about #23 @JonasGeschke.

**Comment by JonasGeschke** [comment]
did my feedback ;-)
thanks for the explanation about the website, got it.

**Comment by KevCaz** [comment]
Well here is the plan for the next few minutes on my side. I'll tag the version and do the first official GH release. Then would you (@JonasGeschke ) like to do the CRAN submission? Then we are ready for the JOSS submission, right? I'm unsure whether or not we should get a DOI (via Zenodo) now or wait for the review.

**Comment by JonasGeschke** [comment]
sounds good!
yeah I can do the CRAN submissen, if you dont like to. I will do the JOSS submission once we have the cran link.
you can do the Zenodo now or wait until the JOSS paper is done. see the review process of the JOSS paper:

<img width="738" alt="bildschirmfoto 2018-07-23 um 17 52 31" src="https://user-images.githubusercontent.com/14090764/43087943-4bc315c6-8ea1-11e8-954b-58d4cac1cbdd.png">

**Comment by KevCaz** [comment]
It's up to you I can handle the CRAN submission and let you handle the JOSS submission.

**Comment by JonasGeschke** [comment]
yeah lets do it that way. I guess for the Zenodo deposit we should wait for the review, in case they ask for edits, right

**Comment by JonasGeschke** [comment]
alright. so I would close here so we can handle each submission separately (as we are doing already).
