### ISSUE TITLE
Token in readme

### ISSUE THREAD

**Issue by ibartomeus** [ropensci/rcites#18]
Do you think is a good idea to add a token to the readme? My understanding is that those should be personal. Hence, I would remove it from there and add a link to get your own token.

**Comment by ibartomeus** [comment]
I edited the vignette explaining a bit more the process.

**Comment by KevCaz** [comment]
Just to be clear I've never provided a real token in the vignette! I was using the one from the API website (which does not work) and was actually using mine from a hidden file that was never put on Github! 

I have however removed this part of the README as we have a website site now!
