### ISSUE TITLE
Vignettes

### ISSUE THREAD

**Issue by ibartomeus** [ropensci/rcites#19]
Should `citesr-vignette.Rmd` live in both `vignettes/` and `inst/doc/` ? Or we can remove one?

**Comment by ibartomeus** [comment]
Also, I am not sure how to link to the html of the vignette (in a readable format) from the readme. I left a not there.

**Comment by KevCaz** [comment]
> Should citesr-vignette.Rmd live in both vignettes/ and inst/doc/ ? Or we can remove one?

It should remain this way!

> Also, I am not sure how to link to the html of the vignette (in a readable format) from the readme. I left a not there

Now we have the website and the vignette is included!

**Comment by ibartomeus** [comment]
Perfect!
