### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by ibartomeus** [ropensci/rcites#20]
I added the R citation to the ms, but I can't edit the .bib, can you please add this and re-knit the .md? Thanks!

**Comment by KevCaz** [comment]
I'll take care of this (tonight)

**Comment by JonasGeschke** [comment]
I added the R citation. I actually dont know if we need to/ should re-knit and even have the output style int the metadata section, as JOSS will produce the paper in the end. At least the expample manuscript at JOSS doesnt have it.

**Comment by JonasGeschke** [comment]
Further procedure: (?)
- Wait for the others if we include them as contributers (but as far as I remember and the github stats say we are the main contributers ;-) ).
- Finalize the vignette (more to do?)
- Submit the package to CRAN
- Add the CRAN link to the paper and submit to JOSS

Anything else?

**Comment by KevCaz** [comment]
> Finalize the vignette (more to do?)

I've added a small example to deal with a vector of species. I should be able to merge it by the end of the day. 

> Anything else? 

I think we're good!

**Comment by ibartomeus** [comment]
Thanks!
