### ISSUE TITLE
CITESR Co-authorship

### ISSUE THREAD

**Issue by ibartomeus** [ropensci/rcites#21]
Dear @JonasGeschke, @KevCaz, @basil-yakimov, @tdjames1,  @susanjarvis501, @mbhleduc, and @JonathanGoldenberg.

Thanks to a big push from Kevin and Jonas, we finalized the R package citesR. We plan to submit it to JOSS soon. As you all participated in the hackathon, we would like to be inclusive and fair in the co-authorship and list all relevant contributions. 

Please, let us know how would you like to be acknowledged. I think the right move would be to list you in the R package as contributors (according to the package author role definitions: "ctb" (Contributor): Authors who have made smaller contributions.), but please, let us know if any of you made substantial contributions in early stages (I don't remember who did what, to be honest, so speak up!), in which case we should list you as Authors ("aut" (Author): Full authors who have made substantial contributions to the package). 

As for the paper authorship, if you want to contribute, please edit the paper.md file with your inputs asap. 

Please, answer in this issue before end of July. 

Best,
Nacho, Jonas and Kevin.

**Comment by Yasmine-Verzelen** [comment]
Hi, thank you so much for finishing the package! I would be honored to be listed as contributor.

Best,

Yasmine

**Comment by basil-yakimov** [comment]
Hi all. No doubt that my contribiton is a strict zero. So please do not mention me as any type of a contributor. But it was a great experience to observe the process of development and submission.
Good luck and well done!

**Comment by JonathanGoldenberg** [comment]
Hi everyone. It is really nice to see how few hours of brainstorming ended up with. Good job guys! As my input was mainly theoretical, I will be happy to be listed as ctb.

Best,
Jonathan

**Comment by JonasGeschke** [comment]
Alright. For those who want to be listed as contributor, **please send your full name until Sunday night** (European time), so we can proceed with submitting the package early next week. Thanks!
(as online user names sometimes are not what one wants so have as author name)

**Comment by KevCaz** [comment]
Orcid would be great! So far @Yasmine-Verzelen  and @JonathanGoldenberg  have been added as contributors! https://ibartomeus.github.io/citesr/authors.html

**Comment by Yasmine-Verzelen** [comment]
Full name: Yasmine Verzelen

**Comment by tdjames1** [comment]
Hi, great job for finishing the package, @JonasGeschke @KevCaz @ibartomeus!

Since I was only really participating in the workshop as a helper, I don't feel as if I've contributed to the development of this package (although apparently I committed the original license file and author list:
https://github.com/ibartomeus/citesr/graphs/contributors) so no need to include me.

Cheers,
Tamora

**Comment by JonathanGoldenberg** [comment]
Full name: Jonathan Goldenberg

Thanks,
Jonathan

**Comment by mbhleduc** [comment]
Hi, I would be delighted to be acknowledged as contributor. Whatever small contributions that I provided, I mostly owe it to the hackaton helper who guided me through a lot of the steps so if you remember her name/contact info, it would be great to list her as well (I unfortunately don`t remember her name!

Marie-Bé Leduc
University of Ottawa

**Comment by KevCaz** [comment]
All good!

https://ibartomeus.github.io/citesr/authors.html

Many thanks @tdjames1
