### ISSUE TITLE
Versioning of the package

### ISSUE THREAD

**Issue by KevCaz** [ropensci/rcites#23]
Hi,

I'm almost done with the first version of the package. I think it should be released under 0.2.0 so versions 0.1.X refer to the first era of the development. You may or may not be familiar with semantic versioning so here is a very helpful link https://semver.org/. I propose we keep using 0.1.X until there is a change in the checklist API. Alternatively we could use 1.X.X so the first number refers to the version of the Checklist API (in which case versions 0.X.X would refer to early development stages). 

Also, we may want to add a 4th number to indicate whether or not it is a development version. For instance, let say 1.1.1 is on CRAN, then we use 1.1.1.900 for the development version, switch to 1.1.2 for the new release and once the release done we then name the dev version 1.1.2.900.  

Let me know what do you think so I properly tag the first version!

**Comment by ibartomeus** [comment]
I agree with whatever you choose.

**Comment by JonasGeschke** [comment]
Hi there,
the most logical one to me would be "I propose we keep using 0.1.X until there is a change in the checklist API." = first release as version 0.1.0

However, I also agree to what you can decide on.
In regard to the 4th number for development version thats fine to me.

**Comment by KevCaz** [comment]
So let's say 0.1.0 as our first version and start from there. I'll tag this version now!

**Comment by JonasGeschke** [comment]
great, thanks!
