### ISSUE TITLE
Logo / sticker

### ISSUE THREAD

**Issue by KevCaz** [ropensci/rcites#24]
In our communication era I think would be great to have a logo/sticker. Nowadays, R community tend to mostly use  hexagon logos, see http://hexb.in/ and the specification here https://github.com/terinjokes/StickersStandard.

Anyone interested in designing the logo of our package?

**Comment by JonasGeschke** [comment]
a very first idea ...

![citesr](https://user-images.githubusercontent.com/14090764/43067604-19289a84-8e68-11e8-84ba-297ac775d431.png)

**Comment by JonasGeschke** [comment]
and a first update, including the database name as well as making the text readable once the picture is smaller in size ...

![citesr_v2](https://user-images.githubusercontent.com/14090764/43068907-0558b0b2-8e6c-11e8-9689-a2a4bf9a207b.png)

![citesr_v2_small](https://user-images.githubusercontent.com/14090764/43068926-1130ff0c-8e6c-11e8-9077-36c1f871ddd6.png)

**Comment by JonasGeschke** [comment]
any feedback to me ;-)

**Comment by KevCaz** [comment]
I think I like the idea of using the picture of an elephant to remember what CITES is about. Is the photo copyrighted? Is there a way I can edit the logo?

**Comment by KevCaz** [comment]
old school feed back!
![suggestkc](https://user-images.githubusercontent.com/1583534/43077678-28e00154-8e56-11e8-8ced-77e9ffb85c6b.png)

**Comment by JonasGeschke** [comment]
indeed, the copyright issue ... resolved. its my own picture now.

![citesr_v3](https://user-images.githubusercontent.com/14090764/43077630-4dbc4a14-8e88-11e8-8542-2412e12fb538.png)

**Comment by JonasGeschke** [comment]
haha great, thanks, I will try my best!

**Comment by JonasGeschke** [comment]
and here we go:
(citesr or citesR? - we would need to change the package documentation respectively ...)

![citesr_v4](https://user-images.githubusercontent.com/14090764/43078428-aeca222a-8e8a-11e8-8ee3-096fc573fd3c.png)

**Comment by KevCaz** [comment]
Nice! I would zoom out slightly (to see a bit more of the elephant). 
Regarding the name of the package I'd keep lower case letters. By the way I thought that *maybe*, **rcites** sounds better than **citesr** and make it more similar to [rfishbase](https://cran.r-project.org/web/packages/rfishbase/rfishbase.pdf) or [rorcid](https://cran.r-project.org/web/packages/rorcid/index.html). What do you think?

**Comment by JonasGeschke** [comment]
okay, I zoom out a bit and also optimize the colors.
well I am used to citesr but I dont mind.

**Comment by KevCaz** [comment]
neither do I, no big deal, @ibartomeus any thought?

**Comment by ibartomeus** [comment]
I don't have aesthetic criteria, but rcites sound ok too. I like the elephant :D

**Comment by JonasGeschke** [comment]
alright, so I will change all documentation to rcites!

![citesr_v4](https://user-images.githubusercontent.com/14090764/43079543-abbfca00-8e8d-11e8-9c83-7172c6f4ca78.png)

**Comment by JonasGeschke** [comment]
@ibartomeus can you rename the repository? and also the title "An r package to access CITES (https://speciesplus.net/) https://ibartomeus.github.io/citesr/" should be updated ...

_An R package to access the CITES Speciesplus database - https://ibartomeus.github.io/rcites/_

Thanks!

**Comment by JonasGeschke** [comment]
oh did I mess up something?

**Comment by ibartomeus** [comment]
Is it save to change the repo name? I can do it asap if you confirm.

**Comment by JonasGeschke** [comment]
@KevCaz this is something for you to confirm.
also, I am sorry indeed for messing up something with my "citesr" to "rcites" changes. I reversed all changes I did and hope it works out again ...

**Comment by JonasGeschke** [comment]
in regards to the logo: you like colors?

![citesr_v4_col](https://user-images.githubusercontent.com/14090764/43082500-82fb1f64-8e94-11e8-8c21-c997f5163e0a.png)

**Comment by KevCaz** [comment]
I tend to prefer black and white!

**Comment by JonasGeschke** [comment]
or another angle of the elephant?

![citesr_v5_col](https://user-images.githubusercontent.com/14090764/43083068-ea195296-8e95-11e8-8b73-6c3f02c0b090.png)
![citesr_v5](https://user-images.githubusercontent.com/14090764/43082892-72dcb704-8e95-11e8-969e-5bf6911cfb1a.png)

@KevCaz sorry for messing up something! but it looks like the fixing worked out. could you change the name and documentation from "citesr" to "rcites"? thanks!

**Comment by KevCaz** [comment]
no worries!

**Comment by KevCaz** [comment]
Like this angle!

**Comment by KevCaz** [comment]
@ibartomeus, 
There is nothing to be worried about, everything should work seamlessly! At most few tweaks here and there. 
However, I guess this will be the last time we do so as we do not intend to generate confusion among potential users.

**Comment by ibartomeus** [comment]
Done!

**Comment by KevCaz** [comment]
I'm on it!

**Comment by KevCaz** [comment]
@JonasGeschke let me know when you have the final version of the logo!

**Comment by JonasGeschke** [comment]
great, thanks for all your efforts!
I guess it is the latter version?! I will prepare the files and send them as a zip.

**Comment by JonasGeschke** [comment]
@KevCaz here its the zip file with the logo. if you need me to adapt anything, tell me.
[rcites_logo.zip](https://github.com/ibartomeus/rcites/files/2219888/rcites_logo.zip)

**Comment by KevCaz** [comment]
I'll take care of it :+1:

**Comment by KevCaz** [comment]
I like it, I guess you've used the max font-size possible for the code parts?

**Comment by JonasGeschke** [comment]
well I adjusted the hexagon size to 5.08cm and then chose a font-size thats readable once the logo is set to 209px width.

**Comment by KevCaz** [comment]
Good job! I've added the logo in the README following recommendations about the size of the logo on pkgdown documentation. https://ibartomeus.github.io/rcites/

**Comment by KevCaz** [comment]
Looks like everything is in order. I'm waiting for 1 build to pass!

**Comment by KevCaz** [comment]
So thanks to @JonasGeschke we have a logo now, so let's close this and open a separate issue for evantual updates of the logo. Feel free to re-open this issue now if you are not quite still happy with the first version of the logo, I am closing this because well, I am happy!
