### ISSUE TITLE
author roles

### ISSUE THREAD

**Issue by JonasGeschke** [ropensci/rcites#25]
@KevCaz I just saw you changed the emails. I think we should adapt the author roles instead ... me as author (as I wrote most of the code) and you as maintainer (as you did and are doing most technical stuff).

further, in case its still possible to change this, I worked on the logo a bit more:
[rcites_logo.zip](https://github.com/ibartomeus/rcites/files/2221106/rcites_logo.zip)

**Comment by KevCaz** [comment]
@JonasGeschke, it makes sense to me. My feeling is that I'll be the maintainer for the first release and whenever you'll be more comfortable with the technical details I've been dealing with, you'll take over and be the maintainer!

**Comment by KevCaz** [comment]
To be clear, 

What makes sense is: nacho + you + me are authors, me as (temporarily) maintainer and you first author on package + paper. And you'll be the next maintainer!

**Comment by JonasGeschke** [comment]
great, I agree on that. thank you for all your efforts!
