### ISSUE TITLE
CRAN submission

### ISSUE THREAD

**Issue by KevCaz** [ropensci/rcites#26]
As I'm completing the first CRAN submission, I'd like to add a couple of notes to make your live easier if you (@JonasGeschke or @ibartomeus ) take care of future submissions: 

1. make sure everything is OK (we did so this morning),

2. edit `r-cran-comments.md` to explain what you did,

3. use the win builder https://win-builder.r-project.org/ (`devtools::build_win()`), which allows you to check the package on window, an email will be sent to the maintainer (I guess @JonasGeschke you've already received two of those!), note that we are currently using Travis and Appveyor and doing a good job regarding the testing of the package. 

As usual Hadley Wickham did a great job explaining everything: http://r-pkgs.had.co.nz/release.html

**Comment by KevCaz** [comment]
Last but not least: `devtools::sumit_cran()`

**Comment by KevCaz** [comment]
Done!

 ```
* building ‘rcites_0.1.0.tar.gz’

Submitting file: /tmp/RtmpqKaqff/rcites_0.1.0.tar.gz
File size: 294.7 Kb
Uploading package & comments
Confirming submission
Package submission successful.
Check your email for confirmation link.
```

I've confirmed the submission! 

![screenshot from 2018-07-23 19-13-06](https://user-images.githubusercontent.com/1583534/43107814-ab57d732-8eac-11e8-9446-45df1b46765e.png)

Let's wait and see!

**Comment by JonasGeschke** [comment]
awesome, thank you so much. looking forward to the feedback and outcome!

**Comment by KevCaz** [comment]
FYI

----------------------------
Dear maintainer,
 
package rcites_0.1.0.tar.gz has been auto-processed and is pending a manual inspection. A CRAN team member will typically respond to you within the next 5 working days. For technical reasons you may receive a second copy of this message when a team member triggers a new check.
 
-----------------------------

All good! For the first submission they must have a look!

**Comment by KevCaz** [comment]
Just to keep you in touch, I've just received an email: 

------------
Thanks, please do not comment out your examples and use \donttest{} instead:

\examples{
   examples for users and checks:
   executable in < 5 sec

   donttest{
       further examples for users (not used for checks)
   }

}

Please fix and resubmit.

---------

I'll do this, it also means that once it's done, everything you be Ok!

**Comment by JonasGeschke** [comment]
Great, thank you!
So probably we get this done some time this week. Will submit the paper to JOSS as soon as I get the CRAN-Link.

(by the way: did you ever re-think to submit the package to rOpenSci? cause they automatically have a JOSS submission included)

**Comment by KevCaz** [comment]
> did you ever re-think to submit the package to rOpenSci? cause they automatically have a JOSS submission included.

I think we should submit to the ROpenSci.

**Comment by JonasGeschke** [comment]
alright.
then I will check for the procedure. cause then we dont need to submit the paper to JOSS.

**Comment by JonasGeschke** [comment]
see here: https://ropensci.github.io/dev_guide/onboarding-guide-for-authors.html
so once the CRAN submission is done, one of us can simply do the submission. it should be all fine ...

**Comment by KevCaz** [comment]
I forgot to confirm the submission...Now it's done. Sorry for that we should get the answer soon!

**Comment by KevCaz** [comment]
Our package is on CRAN! :fireworks:

**Comment by JonasGeschke** [comment]
Yeay, thanks for the information, thanks for all efforts!
