### ISSUE TITLE
ROpenSci review: function prefixes

### ISSUE THREAD

**Issue by JonasGeschke** [ropensci/rcites#29]
regarding the function prefixes:
> The authors use the sppplus_ prefix for some functions, and taxon_ for others. It might be simpler to have all functions retrieving something from the API to start with the same prefix (if you want it shorter, I suggest spl_).

as far as I see we do have
1. `sppplus_` for general access by means of login/token and getting the taxon id through the taxon concept and
2. `taxon_` for receiving data for a specific taxon from the database.

I think this actually is close to what the reviewer asked for ... a few things I would propose to change:
1. `sppplus_simplify()` probably doesnt need a prefix at all?
2. `sppplus_special_case()` should be a helper function?
4. `sppplus_taxonconcept()` could become `taxon_concept()`
4. respectively to the [API documentation](https://api.speciesplus.net/documentation/v1.html), we could use just `get_` instead of `taxon_`

resulting in the following function names:
`token` or `set_token` / `simplify` / `get_taxonconcept` / `get_cites_legislation` / `get_eu_legislation` / `get_distribution` / `get_references`
for the helper functions I then would propose `rcites_` as prefix.

what do you think? if you both agree I would change the prefixes.

**Comment by KevCaz** [comment]
I think I prefer `spl_` as a prefix as suggetsed by the review. `get_` is great but I feel that it can suit pretty much all packages dealing with a web API!

**Comment by JonasGeschke** [comment]
yeah ... to be honest I dont like the `spl_` too much, but it is my personal feeling. `get_` of course fits to overall API packages, however in the API documentation they call it "[GET]", which I think also is a nicely straight forward saying for the vignette and re-understanding if somebody checks out the API documentation.

<img width="386" alt="bildschirmfoto 2018-08-22 um 15 01 46" src="https://user-images.githubusercontent.com/14090764/44465406-bd994100-a61d-11e8-9195-e8151414fb0f.png">

anyhow ... 
so you go for `set_token` / `simplify` / `spl_taxonconcept` / `spl_cites_legislation` / `spl_eu_legislation` / `spl_distribution` / `spl_references` / and `rcites_` for the helper functions

I would go for `get_` but for `spl_` we have a reviewer's opinion ;-)
@ibartomeus what do you think?

**Comment by KevCaz** [comment]
>  they call it "[GET]",

Actually this refers to the fact that they are using a GET method as opposed to a POST method https://www.w3schools.com/tags/ref_httpmethods.asp

**Comment by KevCaz** [comment]
Why not `spp`?

**Comment by JonasGeschke** [comment]
> Actually this refers to the fact that they are using a GET method as opposed to a POST method

ah alright. nevertheless `get_` would have been nice.
`spp_` is fine to me. I actually thought about proposing this.

**Comment by JonasGeschke** [comment]
so how do you like
`set_token` / `simplify` / `spp_taxonconcept` / `spp_cites_legislation` / `spp_eu_legislation` / `spp_distribution` / `spp_references` / and `rcites_` for the helper functions
?

**Comment by JonasGeschke** [comment]
> KevCaz reacted with laugh emoji

it is good I make you happy ;-) will wait for @ibartomeus to vote and then implement the new prefixes tonight.

**Comment by KevCaz** [comment]
Perfect! thanks @JonasGeschke. I may work tonight on the package to remove data table and follow the suggestions regarding the outputs (given the time zone you'll be probably sleeping). I'll work on a separate branch.

**Comment by JonasGeschke** [comment]
alright, so as @ibartomeus didnt say anything but I didnt want to loose track of this, I now changed the prefixes according to what we discussed above. hope all checks work out well ...

**Comment by ibartomeus** [comment]
Ups, I did intend to reply, but my response is clearly not here, sorry. I agree with prefixes!

**Comment by ibartomeus** [comment]
Hey, I did intend to reply, but it didn't work (as I can see now). Sorry. Yes, I am fine with the new prefixes.

**Comment by JonasGeschke** [comment]
new prefixes done.
