### ISSUE TITLE
.Rproj

### ISSUE THREAD

**Issue by JonasGeschke** [ropensci/rcites#30]
After renaming the function prefixes, something still doesnt work. Double checked all files, so I guess there needs to be run something so the automatically created files get updated (roxygen?!).

Further, I notices that we have two .Rproj files. one older one `citesr` and the new `rcites`. can the old one be deleted? (for cleaning up purposes)

**Comment by JonasGeschke** [comment]
also, btw, could you update the package website so that the vignette link from CRAN works? cause we by now have more than 💯 downloads!

**Comment by KevCaz** [comment]
I'll take care of this right now!

**Comment by KevCaz** [comment]
32c2df69ac1ebe5f8a34c73ad8cd5c9f2a06c997 should to the job! If you are Ok, close this!

**Comment by JonasGeschke** [comment]
great, thanks. yes, there are some things that I thought would be the issue. thanks for dealing with it.
