### ISSUE TITLE
Add scope and language parameters

### ISSUE THREAD

**Issue by JonasGeschke** [ropensci/rcites#31]
Hi there,
I now added the `scope=` and `language=` parameters to `spp_cites_legislation()` and `spp_eu_legislation()`, as well as the `language=` parameter to `spp_distribution()`.

Can you please test and check for functionality. thanks.

**Comment by KevCaz** [comment]
Nice! I should be able to look at this tomorrow!

**Comment by JonasGeschke** [comment]
@KevCaz great thanks for reviewing the scope and parameter stuff I made. could you merge the two branches by chance so the master it up-to-date? thx!
and then we should check how the [review edits](https://github.com/ibartomeus/rcites/issues/27#issuecomment-414931715) are going.

**Comment by JonasGeschke** [comment]
as far as I see, the issue is generally done.
