### ISSUE TITLE
Make the vignette more comprehensive

### ISSUE THREAD

**Issue by JonasGeschke** [ropensci/rcites#32]
> Maybe 12?

@ibartomeus yes I think it would be great if you could have a look at the vignette. probably we could also have two files, 
- one **"Get started with rcites"** for explaining how to set the token and apply each function (technical explanation of the package)
and 
- one **"Speciesplus information about the African elephant"** for running through a whole functionality explanation and showcasing the package usage (story telling explanation, incl. the use of other packages like rworldmap)
?

If you like this idea I am also happy to kickstart the two files and then we can work on them together.

**Comment by JonasGeschke** [comment]
In [Get started with rcites](https://github.com/ibartomeus/rcites/blob/master/vignettes/get_started.Rmd) and [Speciesplus information about the African elephant](https://github.com/ibartomeus/rcites/blob/master/vignettes/elephant.Rmd) I quickly drafted what it could look like. tell how you like it.

**Comment by KevCaz** [comment]
Thanks! Looks good! 

I'm revisiting several aspects of the package to better use the API, I'll let you what are the new features that should be included in the vignette!

**Comment by ibartomeus** [comment]
Vignettes look great. I'll wait to have the full package with pagination to test the package and update them.

**Comment by KevCaz** [comment]
In all vignette when we use the false token, i.e. `token = "8QW6Qgh57sBG2k0gtt"`, the code chunk must be set to `eval=FALSE`, for instance:

    ```{r, eval = FALSE}
     res1 <- spp_taxonconcept(query_taxon = "Loxodonta africana", token = "8QW6Qgh57sBG2k0gtt")
    ```

or

    ```{r, eval = FALSE}
     set_token("8QW6Qgh57sBG2k0gtt")
    ```
 
Otherwise,when we build the vignette, we get the following error: 

```
Error: processing vignette 'rcites-vignette.Rmd' failed with diagnostics:
Unauthorized (HTTP 401).
```

**Comment by JonasGeschke** [comment]
@ibartomeus yes sure, we should wait for all functions and the 2nd review (=> potential change) to be done before doing the documentation.
@KevCaz thanks for the info, done.

**Comment by JonasGeschke** [comment]
So we now have 3 vignettes:
1. Get started
2. Bulk analysis
3. Elephant

_Get started_ is pretty much done. _Bulk analysis_ looks basic, but I think is fine. _Elephant_ needs some more work, as this should explain a whole workflow with the package and make the outputs understandable.
I will continue working on it this week. @ibartomeus do you have some time, too?

**Comment by ibartomeus** [comment]
Yes, sorry for my lack of time. I'll run everything to see how it works and any potential improvement and work on the vignettes a bit.

**Comment by KevCaz** [comment]
> Bulk analysis looks basic, but I think is fine. 

I'll add some text to give more details. 

FWIW. my vision is:
- "get_started" for a short overview;
- "elephant" to give examples of  what you can do with the data for one taxon;
- "bulk analaysis" show how to use the package to get data for many taxa;

**Comment by JonasGeschke** [comment]
Alright, I just had a look at all of the three and cleaned up "elephant". I dont think you need to give "bulk analysis" more text, as it pretty clearly shows how to do/code this. The only thing that could be added, as the same with "elephant" now, is some explanation about the outputs.

Regarding the development of "elephant" as case study: Your idea with the map of trade directions is great and should be doable. However, in light of the time period gone past since the reviews came in, I think we should be good to go and add more details and use examples bit by bit. Like I think the package functioning is advanced quite a lot so we should not wait too long just because of some use examples ...

**Comment by KevCaz** [comment]
I do agree that the time has come to send the revised package back to the reviewers. I'll have a last check latter today. Let say we submit our revised Monday (or before if you are available)?

**Comment by JonasGeschke** [comment]
Perfect.
As far as I see you can do your last check (@ibartomeus you need some more time if you want to add something before re-submission? however can do more work and add use examples at any time ;-) ) and post the answer to reviewers thereafter. If you prefer, also I can do this.
Then we need to wait for their response and hopefully approval. Thereafter, we will need to do [some more things](https://ropensci.github.io/dev_guide/onboarding-guide-for-editors.html#during-review) in order to have the package with rOpenSci ...

**Comment by JonasGeschke** [comment]
It seems like @ibartomeus doenst have too much time these days (which is fine). So @KevCaz did you do the last check? Any issues that came up and you need help with?
If not, would you rebuild the website so we can post the answer text to the reviewers?

**Comment by ibartomeus** [comment]
I can do it today (and I'll be happy to look through everything, even if my comments will be very minor or non-existing, giving your amazing job)! Sorry again.

**Comment by JonasGeschke** [comment]
No worries at al @ibartomeus! We all have other duties to deal with, so it is fine. Special thanks in this regard to @KevCaz for dealing with all the technical issues!
So I guess we are good to go and get the package resubmitted asap.

**Comment by ibartomeus** [comment]
What the 'load_all()' function is doing in line 53 of the get_started vignette? it fails for me ('Error in load_all() : could not find function "load_all"').

Ok, it knits correctly, but if fails when ran as stand alone.

**Comment by KevCaz** [comment]
@ibartomeus I used it for some reasons (bad reasons) it should be replaced by `library(rcites)`.

**Comment by ibartomeus** [comment]
Ok, I'll do that!

**Comment by ibartomeus** [comment]
Can we also remove !-- https://cran.r-project.org/web/packages/httr/vignettes/secrets.html --
from line 24 on elephant.rmd?

**Comment by KevCaz** [comment]
Yep

Em Seg, 15 de out de 2018 07:58, Ignasi Bartomeus <notifications@github.com>
escreveu:

**Comment by ibartomeus** [comment]
I found one bug in Bulk analysis: 

> res_cms <- spp_taxonconcept("", taxonomy = "CMS") 
Retrieving info from page  6 / 6 
Done!
Error in do.call(rbind, y[[name]]) : second argument must be a list
> dim(res_cms$general)
NULL

**Comment by ibartomeus** [comment]
Ok, other than the bug above, I corrected a few typos and made a few clarifications. All pushed. @KevCaz make a quick look to check I didn't add anything wrong and let's submit it! The package looks impressive!

**Comment by KevCaz** [comment]
I'll have the final look, I was suppose to do that during the week-end but did not find the time to do so! 
Thanks @ibartomeus!

**Comment by KevCaz** [comment]
All fixed, website rebuilt. I think we can close this for now and open a new issue when the time of reviewing the vignettes will come.
