### ISSUE TITLE
Add parameters to spp_taxonconcept

### ISSUE THREAD

**Issue by JonasGeschke** [ropensci/rcites#33]
Hi @KevCaz, depending on how you are going with adaptions to `spp_taxonconcept`, we could further consider to add more parameters to the function. The API provides quite a few, but for the start I would think `with_descendants` and again `language` could be quite handy ones. right now the function is based on `name` only.

<img width="793" alt="bildschirmfoto 2018-08-26 um 10 44 40" src="https://user-images.githubusercontent.com/14090764/44626484-88db0180-a91d-11e8-9060-1f11592eb5e0.png">

**Comment by KevCaz** [comment]
a09a9ac810a071fb1c93c644640534b192bc7608 introduces a new version of `spp_taxonconcept()` that includes these parameters! The only one missing is `updated_since` but I should be able to include it sooner than latter. 

This function will require a new set of tests, a better documentation, which will require some work... That being said the auto-pagination is now implemented and it is now straightforward to retrieve pretty much anything (I mean all the data base within one command line!).

**Comment by JonasGeschke** [comment]
Nice! looking forward to the function!

a few questions from my side:

1. wouldnt it be nicer to set the `taxonomy = c("CITES", "CMS)` in the function and then calling the taxonomy check `taxonomy <- match.arg(taxonomy)` which then either takes the first argument CITES or checks that CMS is in the vector and gives an error message with information whats the values if something else is given as argument. (actually I wouldnt have included this argument for now, as the package only accesses CITES data and not CMS data. but not we have it in there, its fine.)

2. dont you want to put all helper functions that cannot be called themselves (which I understand is special with `rcites_simplify()`) into the zzz.R document (also: now we have two `rcites_specialcase()` functions?!)

3. I dont really understand the 

> I mean all the data base within one command line!

you mean like the `spp_taxonconcept()` function does all legislation access, too?

3. actually not a question: tell if you need help with the documentation. but you know best what you have coded ;-) also we then need a pull request of your branch so we can fully work on it, too. I mean that we have all package content all together again.

**Comment by KevCaz** [comment]
1. Good point! done! 
2. Again good point, done! 
3. So I meant that if you sent an empty query then you'll retrieve all the data base! (just for `spp_taxonconcept()`)
4. I'll need some help with the documentation, I'll let you know how you can help!

**Comment by KevCaz** [comment]
Regarding `updated_since` ISO 8601 is needed http://api.speciesplus.net/documentation/v1/taxon_concepts/index.html
I found this https://stackoverflow.com/questions/29517896/current-time-in-iso-8601-format

**Comment by JonasGeschke** [comment]
@KevCaz 
regarding `<- match.arg()` as far as I understand it is sufficient if we place "taxonomy" in the function, without the choices, as we only have those choices set in the function itself, without further alternative options.

> So I meant that if you sent an empty query then you'll retrieve all the data base! (just for spp_taxonconcept())

Sounds nice indeed, I am looking forward to it!

Regarding the date-time ISO: I worked with `as.POSIXlt` before, so if you need help I can work myself into that stuff again.

**Comment by JonasGeschke** [comment]
> regarding <- match.arg() as far as I understand it is sufficient if we place "taxonomy" in the function, without the choices, as we only have those choices set in the function itself, without further alternative options.

ah I saw you changed something in the other functions, too. looks fancy, how you put everything into its own helper function. but efficient 👍

**Comment by JonasGeschke** [comment]
as far as I see, the issue is generally done.
