### ISSUE TITLE
Blog post for Ropensci website and MEE

### ISSUE THREAD

**Issue by KevCaz** [ropensci/rcites#40]
@ibartomeus started this https://docs.google.com/document/d/1ddyBaaSl8Q20tcjpTYMgAAUT7TP9LMRZgDNugC4ierM/edit?usp=sharing

I thought I'd be clearer to have a separate issue for this :)

**Comment by ibartomeus** [comment]
Thanks! I'll also fork the ropensci repo for posts and move the content there. Should we do the same post for MEE and ropensci? Or is it worth it to do two different entries? tagging @JonasGeschke here,

**Comment by KevCaz** [comment]
As the post should be written in Markdown I now am writing using markdown tags. Also, I've included the YAML header.

**Comment by KevCaz** [comment]
Thanks @ibartomeus for the draft, I gave it a first go, happy to give another latter!

**Comment by JonasGeschke** [comment]
Hi, just so you know I submitted the paper to JOSS. will let you know about the process.
Regarding the blog post: thanks for starting the draft! will have a look at it tomorrow.

Do we want to submit the same blog post to both blogs?

**Comment by JonasGeschke** [comment]
> Should we do the same post for MEE and ropensci? Or is it worth it to do two different entries? tagging @JonasGeschke here,

Ah here I just found the same question. I actually think one blog post for both blogs would be fine, they can also refer to each other. or we can do a blog post for MEE and a technical note for ROpenSci ...

**Comment by KevCaz** [comment]
My opinion is that we should do the post for Ropensci and then mention the post to MEE and ask them if they are interested in hosting the same post / if they want something different / or just a quick abstract + the link to the Ropensci post. Just my opinion, not a strong one, happy to go in any direction.  

I'd also like to mention that I will also do a post on my blog about this. But it'll be a bit different as it is a way for me to gather general thoughts about packages. I'll let you know about this one (may be soon, may be not that soon haha),

**Comment by ibartomeus** [comment]
I agree with Kevin, let's just ask MEE once the other one is published.

**Comment by JonasGeschke** [comment]
> let's just ask MEE once the other one is published.

great to then thats the way we go.

**Comment by JonasGeschke** [comment]
So now I also did my read and edits to the blog post. @ibartomeus can you run through the proposed changes to make it a clean text?

**Comment by ibartomeus** [comment]
Done, if you are happy, I can fork the ropensci blog repo and, add our post, and do the pull request. Just give me your green light.

**Comment by JonasGeschke** [comment]
I just changed the "MEE hackathon" to "Ecology Hackathon", so we dont exclude other organisers.
with this, you have my green light!

**Comment by KevCaz** [comment]
@ibartomeus I edited (slightly) the post. I would have loved to find the real name of T. D. James... 
Green light.

**Comment by JonasGeschke** [comment]
> I would have loved to find the real name of T. D. James...

Tamora James? => https://rse.shef.ac.uk/blog/sheffieldR-hacktoberfest/ and https://twitter.com/soayipm

**Comment by KevCaz** [comment]
Yeah!! I added here names, thanks @JonasGeschke

**Comment by JonasGeschke** [comment]
I just cleaned up all links. anything else @KevCaz?
from my side its looking good and can be submitted @ibartomeus

**Comment by KevCaz** [comment]
All good!

**Comment by KevCaz** [comment]
@JonasGeschke and @ibartomeus, all done?

**Comment by ibartomeus** [comment]
Yep: https://github.com/ropensci/roweb2/pull/344 waiting for publication.

**Comment by tdjames1** [comment]
> > I would have loved to find the real name of T. D. James...
> 
> Tamora James? => https://rse.shef.ac.uk/blog/sheffieldR-hacktoberfest/ and https://twitter.com/soayipm

That's right - thanks for the mention :)

**Comment by KevCaz** [comment]
Just to be sure, @ibartomeus you will handle the edition of the post?

**Comment by ibartomeus** [comment]
Yes.
