### ISSUE TITLE
JOSS publication

### ISSUE THREAD

**Issue by JonasGeschke** [ropensci/rcites#41]
Hi there,
you guys quickly want to proof-read? As far as I see, it's all fine.

https://github.com/openjournals/joss-papers/blob/joss.01090/joss.01090/10.21105.joss.01090.pdf

**Comment by ibartomeus** [comment]
Looks great!

My affiliation should be "Estación Biológica de Doñana (EBD-CSIC)". Can you check that. Thanks.

I am not familiar with the meaning of "n.d.", but I Think it is correct. Nothing else to add.

**Comment by JonasGeschke** [comment]
Alright. Are you fine with "Estación Biológica de Doñana, Spain"?

"n.d." means no date, which is/ can be used for websites. but happy if you have an other style.

**Comment by ibartomeus** [comment]
"(EBD-CSIC)" should be mentioned too.

**Comment by JonasGeschke** [comment]
so it is "Estación Biológica de Doñana (EBD-CSIC), Spain".
alright?

**Comment by JonasGeschke** [comment]
@KevCaz your affiliation is okay?

**Comment by KevCaz** [comment]
Yep my affiliation is correct! 

Also I wonder, should we use Speciesplus or Species+ (not a big deal though).

Thanks!

**Comment by JonasGeschke** [comment]
Great. I took the double "Guelph" out though. ok?

I changed it all to Speciesplus, expect the one/first time in the text here we have the brakets.

**Comment by KevCaz** [comment]
> Department of Integrative Biology, University Of Guelph, Guelph, Ontario, Canada

Is correct

>  Guelph, Ontario, Canada

city/province/Country I guess it is needed.

**Comment by JonasGeschke** [comment]
so this is it:

affiliations:
- index: 1
  name: Museum für Naturkunde Berlin - Leibniz Institute for Research on Evolution and Biodiversity, Berlin, Germany
- index: 2
  name: Department of Integrative Biology, University Of Guelph, Guelph, Ontario, Canada
- index: 3
  name: Estación Biológica de Doñana (EBD-CSIC), Sevilla, Spain

**Comment by ibartomeus** [comment]
Perfect, great!

**Comment by JonasGeschke** [comment]
submission is done, paper is accepted, I will post the DOI as soon as I got it.

**Comment by JonasGeschke** [comment]
https://doi.org/10.21105/joss.01091

**Comment by KevCaz** [comment]
that fast?? :smile:

**Comment by JonasGeschke** [comment]
yep, because we ran through the rOpenSci review process already.
