### ISSUE TITLE
Error when requesting all taxon identifiers

### ISSUE THREAD

**Issue by JonasGeschke** [ropensci/rcites#42]
Hi @KevCaz, besides the CBD COP-14 I just did a request of all Speciesplus taxon identifiers. Unfortunately, an error popped up, which we should have a look at.

<img width="590" alt="all_taxa_error" src="https://user-images.githubusercontent.com/14090764/48932574-613c0b00-ef05-11e8-8851-e70cc3653d55.png">

**Comment by KevCaz** [comment]
@JonasGeschke Did the error pop at page 3?

**Comment by JonasGeschke** [comment]
@KevCaz no it came after the whole 154 pages only. I actually dont know why it has a double "Retrieving info from page X/Y" info.

**Comment by JonasGeschke** [comment]
@KevCaz no it came after the whole 154 pages only. I actually dont know why it has a double "Retrieving info from page X/Y" info.

**Comment by KevCaz** [comment]
Ok I can reproduce it. I guess there is a least on page that causes an issue!

**Comment by KevCaz** [comment]
At least page 19 leads to this issue. I'll see what I can do this WE.

**Comment by KevCaz** [comment]
Related to this: 

```
R> taxa <- spp_taxonconcept("", page = 111:112)
Retrieving info from page  112 / 154
Done!
Error in do.call(rbind, y$cites_listings) :
  second argument must be a list
```

**Comment by KevCaz** [comment]
Found the first one, due to `hash_annotation` that may have 2 elements... I'm on it.

**Comment by KevCaz** [comment]
Found the second one too, sometime there are no `cites_listings` for an entire pages!

**Comment by KevCaz** [comment]
a new one: 

```R
res1 <- spp_taxonconcept("", pages = 83)
Error in do.call(rbind, y$cites_listings) :
  second argument must be a list
```

**Comment by KevCaz** [comment]
Sounds like I got it! 

```R
R> gg <- spp_taxonconcept("", pages = 1:154)
Retrieving info from page  154 / 154        
Done!
```

**Comment by KevCaz** [comment]
To fix this issue, I reviewed `rcites_taxonconcept_cites_listings()` + `rcites_unlist_party()` (which now is `rcites_party()`) in `zzz.R` I also added a test to include page 83 which is the page where the filed `cites_listing` vanishes.
