### ISSUE TITLE
Why `sppplus` and not `spplus`?

### ISSUE THREAD

**Issue by KevCaz** [ropensci/rcites#7]
Currently we use `sppplus` as a suffix for function. I do not recall why there are 3 p? 
Should we rather use `spplus`?

**Comment by JonasGeschke** [comment]
Hi all,
continuing working on the package still is on my list - also preparing a manuscript about it.
So far we use 3p, as it is „spp“ „plus“…

**Comment by KevCaz** [comment]
Sounds good 😄 !

I'm working on it right now (on a separate branch). Hopefully some issues will be fixed today.

**Comment by ibartomeus** [comment]
Great, Jonas, add the ms to the repo and I can try to contribute whenever I find the time.

**Comment by KevCaz** [comment]
Let's keep `sppplus`.
